version: "3.7"

services:
  pokecenter_db:
    image: postgres
    container_name: pokecenter_db
    env_file: ./.env
    networks:
      - pokecenter_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      timeout: 10s
      retries: 5
      start_period: 5s

  pokecenter_backend:
    build:
      context: .
    container_name: pokecenter_backend
    env_file: ./.env
    depends_on:
      pokecenter_db:
        condition: service_healthy
    networks:
      - pokecenter_network
    ports:
      - 5000:5000

networks:
  pokecenter_network:
    driver: bridge
    name: pokecenter_network
